name: omi_sdk_example
description: Example app demonstrating Omi SDK usage
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add your local SDK as a path dependency
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  path: ^1.8.3
  omi_sdk:
    path: ../
  # Add cupertino_icons for iOS-style icons
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
