name: omi_sdk
description: Flutter SDK for Omi devices
version: 1.0.0
homepage: "github.com/DevMaan707/omi_sdk"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.12.13
  web_socket_channel: ^2.4.0
  opus_flutter: ^3.0.3
  opus_dart: ^3.0.1
  flutter_sound: ^9.2.13
  permission_handler: ^11.0.1
  flutter_foreground_task: ^6.0.0+1
  audioplayers: ^6.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
